# Generated by Django 3.0.1 on 2020-02-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Author')),
            ],
        ),
    ]
